# Get the electricity energy mix data

We use https://www.globalpetrolprices.com/energy_mix.php that use calculations based on data from the U.S. Energy Information Administration

In [46]:
# hide
# Permet d'afficher plusieurs sorties dans une mÃªme cellule de Jupyter
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

https://www.globalpetrolprices.com/energy_mix.php

Data is from 2018 to 2020 depending of the country.

https://unfccc.int/ghg-inventories-annex-i-parties/2021 is maybe better but more difficult to use.

https://www.globalpetrolprices.com/custom_graphic_ge.php?requestType=2&type=1&from=2019&to=2021&width=730&height=400&widthPercent=80&heightPercent=60&legend=bottom&indicator_url=fossil_fuels_electricity_generation,wind_electricity_generation,solar_electricity_generation,hydroelectricity_generation,nuclear_power_generation,geothermal_electricity_generation&unit=194

In [103]:
base_url = "https://www.globalpetrolprices.com/custom_graphic_ge.php?requestType=2&type=1&from=1980&to=2021&width=730&height=400&widthPercent=80&heightPercent=60&legend=bottom&indicator_url=fossil_fuels_electricity_generation,wind_electricity_generation,solar_electricity_generation,hydroelectricity_generation,nuclear_power_generation,geothermal_electricity_generation&unit="
countries = [107,179,52,53,2,3,108,4,160,181,5,6,109,110,7,182,183,8,54,9,111,10,184,55,11,56,185,57,113,58,114,59,13,60,61,62,15,115,16,63,186,18,187,188,189,190,64,19,20,21,65,22,66,67,191,68,192,162,193,194,69,70,119,195,71,196,197,26,27,72,73,28,29,30,120,199,200,121,122,123,124,201,125,202,74,31,126,127,128,75,164,129,130,76,203,131,77,78,79,205,206,132,80,81,133,134,82,208,83,84,32,209,137,211,212,86,87,88,138,213,166,167,34,89,90,139,207,214,140,141,35,171,36,37,143,215,216,39,144,91,217,218,145,42,44,172,92,146,93,220,94,95,147,221,222,173,96,97,148,223,149,98,45,99,224,225,150,151,152,100,153,101,175,46,102,226,154,103,227,155,228,49,48,156,177,51,157,158,105,106]
country_id = 179
import requests
import pandas as pd
from time import sleep

In [111]:
len(countries)

190

In [104]:
def get_url(country_id):
    # Retreive the content
    try:
        r = requests.get(base_url + str(country_id))
        content = r.text
        if r.status_code != 200:
            print(f'ERROR HTTP : {r.status_code} for {url}')
            return None
        if len(r.content) < 1_000:
            print(f'ERROR HTTP content too small : {content} for {url}')
            return None
        return content
    except:
        logger.error(f'Unexpected ERROR for {url}: {sys.exc_info()[0]}')
        return None

In [105]:
countries = {
    "107":"Afghanistan",
    "179":"Albania",
    "52":"Algeria",
    "53":"Angola",
    "2":"Antigua and Barbuda",
    "3":"Argentina",
    "108":"Armenia",
    "4":"Aruba",
    "160":"Australia",
    "181":"Austria",
    "5":"Azerbaijan",
    "6":"Bahamas",
    "109":"Bahrain",
    "110":"Bangladesh",
    "7":"Barbados",
    "182":"Belarus",
    "183":"Belgium",
    "8":"Belize",
    "54":"Benin",
    "9":"Bermuda",
    "111":"Bhutan",
    "10":"Bolivia",
    "184":"Bosnia and Herzegovina",
    "55":"Botswana",
    "11":"Brazil",
    "56":"Brunei",
    "185":"Bulgaria",
    "57":"Burkina Faso",
    "113":"Burma (Myanmar)",
    "58":"Burundi",
    "114":"Cambodia",
    "59":"Cameroon",
    "13":"Canada",
    "60":"Cape Verde",
    "61":"Central African Republic",
    "62":"Chad",
    "15":"Chile",
    "115":"China",
    "16":"Colombia",
    "63":"Comoros",
    "186":"Croatia",
    "18":"Cuba",
    "187":"Cyprus",
    "188":"Czechia",
    "189":"Democratic Republic of the Congo",
    "190":"Denmark",
    "64":"Djibouti",
    "19":"Dominica",
    "20":"Dominican Republic",
    "21":"Ecuador",
    "65":"Egypt",
    "22":"El Salvador",
    "66":"Equatorial Guinea",
    "67":"Eritrea",
    "191":"Estonia",
    "68":"Ethiopia",
    "192":"Faroe Islands",
    "162":"Fiji",
    "193":"Finland",
    "194":"France",
    "69":"Gabon",
    "70":"Gambia",
    "119":"Georgia",
    "195":"Germany",
    "71":"Ghana",
    "196":"Gibraltar",
    "197":"Greece",
    "26":"Grenada",
    "27":"Guatemala",
    "72":"Guinea",
    "73":"Guinea-Bissau",
    "28":"Guyana",
    "29":"Haiti",
    "30":"Honduras",
    "120":"Hong Kong",
    "199":"Hungary",
    "200":"Iceland",
    "121":"India",
    "122":"Indonesia",
    "123":"Iran",
    "124":"Iraq",
    "201":"Ireland",
    "125":"Israel",
    "202":"Italy",
    "74":"Ivory Coast",
    "31":"Jamaica",
    "126":"Japan",
    "127":"Jordan",
    "128":"Kazakhstan",
    "75":"Kenya",
    "164":"Kiribati",
    "129":"Kuwait",
    "130":"Kyrgyzstan",
    "76":"Laos",
    "203":"Latvia",
    "131":"Lebanon",
    "77":"Lesotho",
    "78":"Liberia",
    "79":"Libya",
    "205":"Lithuania",
    "206":"Luxembourg",
    "132":"Macao",
    "80":"Madagascar",
    "81":"Malawi",
    "133":"Malaysia",
    "134":"Maldives",
    "82":"Mali",
    "208":"Malta",
    "83":"Mauritania",
    "84":"Mauritius",
    "32":"Mexico",
    "209":"Moldova",
    "137":"Mongolia",
    "211":"Montenegro",
    "212":"Montserrat",
    "86":"Morocco",
    "87":"Mozambique",
    "88":"Namibia",
    "138":"Nepal",
    "213":"Netherlands",
    "166":"New Caledonia",
    "167":"New Zealand",
    "34":"Nicaragua",
    "89":"Niger",
    "90":"Nigeria",
    "139":"North Korea",
    "207":"North Macedonia",
    "214":"Norway",
    "140":"Oman",
    "141":"Pakistan",
    "35":"Panama",
    "171":"Papua New Guinea",
    "36":"Paraguay",
    "37":"Peru",
    "143":"Philippines",
    "215":"Poland",
    "216":"Portugal",
    "39":"Puerto Rico",
    "144":"Qatar",
    "91":"Republic of the Congo",
    "217":"Romania",
    "218":"Russia",
    "145":"Rwanda",
    "42":"Saint Lucia",
    "44":"Saint Vincent and the Grenadines",
    "172":"Samoa",
    "92":"Sao Tome and Principe",
    "146":"Saudi Arabia",
    "93":"Senegal",
    "220":"Serbia",
    "94":"Seychelles",
    "95":"Sierra Leone",
    "147":"Singapore",
    "221":"Slovakia",
    "222":"Slovenia",
    "173":"Solomon Islands",
    "96":"Somalia",
    "97":"South Africa",
    "148":"South Korea",
    "223":"Spain",
    "149":"Sri Lanka",
    "98":"Sudan",
    "45":"Suriname",
    "99":"Swaziland",
    "224":"Sweden",
    "225":"Switzerland",
    "150":"Syria",
    "151":"Taiwan",
    "152":"Tajikistan",
    "100":"Tanzania",
    "153":"Thailand",
    "101":"Togo",
    "175":"Tonga",
    "46":"Trinidad and Tobago",
    "102":"Tunisia",
    "226":"Turkey",
    "154":"Turkmenistan",
    "103":"Uganda",
    "227":"Ukraine",
    "155":"United Arab Emirates",
    "228":"United Kingdom",
    "49":"Uruguay",
    "48":"USA",
    "156":"Uzbekistan",
    "177":"Vanuatu",
    "51":"Venezuela",
    "157":"Vietnam",
    "158":"Yemen",
    "105":"Zambia",
    "106":"Zimbabwe",
}

In [93]:
def get_df(country_id):
    print("Processing", countries[str(country_id)])
    r = get_url(country_id)
    begin = r.find('arrayToDataTable')+len('arrayToDataTable')+15
    end = r.find('options') - 31
    data = r[begin:end]
    data = data.split('],[')
    data_clean = data.copy()
    for i, d in enumerate(data):
        d = d.replace("'", "").replace("]", "").replace("[", "")
        line = d.split(",")
        # line[0] = line[0].replace("'", "")
        data_clean[i]=line
    df = pd.DataFrame(data_clean[1:], columns=data_clean[0])
    df['country_id'] = country_id
    df['country_name'] = countries[str(country_id)]
    return df

In [95]:
df_qatar = get_df(144)
df_france = get_df(194)

Processing Qatar
Processing France

In [99]:
df_qatar.head(3)

,Year,Fossil fuels electricity generation,Geothermal electricity generation,Hydroelectricity generation,Nuclear power generation,Solar electricity generation,Wind electricity generation,country_id,country_name
0,1980,2.276,0,0.00000,0.00000,0,0,144,Qatar
1,1981,2.596,0,0.00000,0.00000,0,0,144,Qatar
2,1982,2.893,0,0.00000,0.00000,0,0,144,Qatar

In [102]:
pd.concat([df_france, df_qatar], ignore_index=True).sample(10)

,Year,Fossil fuels electricity generation,Geothermal electricity generation,Hydroelectricity generation,Nuclear power generation,Solar electricity generation,Wind electricity generation,country_id,country_name
56,1995,5.617,0,0.00000,0.00000,0,0,144,Qatar
62,2001,9.354,0,0.00000,0.00000,0,0,144,Qatar
5,1985,52.251,0,60.24800,211.19200,0,0,194,France
38,2018,44.4009,0.117,64.48500,393.20001,10.569,28.599,194,France
40,2020,44.553,0.155753680282,60.75027,335.41461,14.1455621272,43.5316709709,194,France
39,2019,48.09322,0.16,56.98242,382.40302,11.668,37.429475,194,France
44,1983,3.116,0,0.00000,0.00000,0,0,144,Qatar
24,2004,51.52328,0,59.27600,425.82901,0.009,0.594,194,France
63,2002,10.284,0,0.00000,0.00000,0,0,144,Qatar
0,1980,117.986,0,68.25300,63.42400,0,0,194,France

In [108]:
!rm world_energy_mix.csv

In [109]:
df_full = pd.DataFrame()
for country_id in countries:
    df = get_df(country_id)
    df_full = pd.concat([df_full, df], ignore_index=True)
    df_full.to_csv('world_energy_mix.csv')
    sleep(1)

Processing Afghanistan
Processing Albania
Processing Algeria
Processing Angola
Processing Antigua and Barbuda
Processing Argentina
Processing Armenia
Processing Aruba
Processing Australia
Processing Austria
Processing Azerbaijan
Processing Bahamas
Processing Bahrain
Processing Bangladesh
Processing Barbados
Processing Belarus
Processing Belgium
Processing Belize
Processing Benin
Processing Bermuda
Processing Bhutan
Processing Bolivia
Processing Bosnia and Herzegovina
Processing Botswana
Processing Brazil
Processing Brunei
Processing Bulgaria
Processing Burkina Faso
Processing Burma (Myanmar)
Processing Burundi
Processing Cambodia
Processing Cameroon
Processing Canada
Processing Cape Verde
Processing Central African Republic
Processing Chad
Processing Chile
Processing China
Processing Colombia
Processing Comoros
Processing Croatia
Processing Cuba
Processing Cyprus
Processing Czechia
Processing Democratic Republic of the Congo
Processing Denmark
Processing Djibouti
Processing Dominica
Processing Dominican Republic
Processing Ecuador
Processing Egypt
Processing El Salvador
Processing Equatorial Guinea
Processing Eritrea
Processing Estonia
Processing Ethiopia
Processing Faroe Islands
Processing Fiji
Processing Finland
Processing France
Processing Gabon
Processing Gambia
Processing Georgia
Processing Germany
Processing Ghana
Processing Gibraltar
Processing Greece
Processing Grenada
Processing Guatemala
Processing Guinea
Processing Guinea-Bissau
Processing Guyana
Processing Haiti
Processing Honduras
Processing Hong Kong
Processing Hungary
Processing Iceland
Processing India
Processing Indonesia
Processing Iran
Processing Iraq
Processing Ireland
Processing Israel
Processing Italy
Processing Ivory Coast
Processing Jamaica
Processing Japan
Processing Jordan
Processing Kazakhstan
Processing Kenya
Processing Kiribati
Processing Kuwait
Processing Kyrgyzstan
Processing Laos
Processing Latvia
Processing Lebanon
Processing Lesotho
Processing Liberia
Processing Libya
Processing Lithuania
Processing Luxembourg
Processing Macao
Processing Madagascar
Processing Malawi
Processing Malaysia
Processing Maldives
Processing Mali
Processing Malta
Processing Mauritania
Processing Mauritius
Processing Mexico
Processing Moldova
Processing Mongolia
Processing Montenegro
Processing Montserrat
Processing Morocco
Processing Mozambique
Processing Namibia
Processing Nepal
Processing Netherlands
Processing New Caledonia
Processing New Zealand
Processing Nicaragua
Processing Niger
Processing Nigeria
Processing North Korea
Processing North Macedonia
Processing Norway
Processing Oman
Processing Pakistan
Processing Panama
Processing Papua New Guinea
Processing Paraguay
Processing Peru
Processing Philippines
Processing Poland
Processing Portugal
Processing Puerto Rico
Processing Qatar
Processing Republic of the Congo
Processing Romania
Processing Russia
Processing Rwanda
Processing Saint Lucia
Processing Saint Vincent and the Grenadines
Processing Samoa
Processing Sao Tome and Principe
Processing Saudi Arabia
Processing Senegal
Processing Serbia
Processing Seychelles
Processing Sierra Leone
Processing Singapore
Processing Slovakia
Processing Slovenia
Processing Solomon Islands
Processing Somalia
Processing South Africa
Processing South Korea
Processing Spain
Processing Sri Lanka
Processing Sudan
Processing Suriname
Processing Swaziland
Processing Sweden
Processing Switzerland
Processing Syria
Processing Taiwan
Processing Tajikistan
Processing Tanzania
Processing Thailand
Processing Togo
Processing Tonga
Processing Trinidad and Tobago
Processing Tunisia
Processing Turkey
Processing Turkmenistan
Processing Uganda
Processing Ukraine
Processing United Arab Emirates
Processing United Kingdom
Processing Uruguay
Processing USA
Processing Uzbekistan
Processing Vanuatu
Processing Venezuela
Processing Vietnam
Processing Yemen
Processing Zambia
Processing Zimbabwe

In [110]:
df_full

,Year,Fossil fuels electricity generation,Geothermal electricity generation,Hydroelectricity generation,Nuclear power generation,Solar electricity generation,Wind electricity generation,country_id,country_name
0,1980,0.231,0,0.71100,0.00000,0,0,107,Afghanistan
1,1981,0.271,0,0.72100,0.00000,0,0,107,Afghanistan
2,1982,0.245,0,0.70700,0.00000,0,0,107,Afghanistan
3,1983,0.254,0,0.74600,0.00000,0,0,107,Afghanistan
4,1984,0.262,0,0.75700,0.00000,0,0,107,Afghanistan
...,...,...,...,...,...,...,...,...,...
7632,2015,4.31178,0,4.94000,0.00000,0.008,0,106,Zimbabwe
7633,2016,3.71488,0,2.95500,0.00000,0.009,0,106,Zimbabwe
7634,2017,3.21856,0,3.92900,0.00000,0.011,0,106,Zimbabwe
7635,2018,3.93202,0,5.00000,0.00000,0.014,0,106,Zimbabwe
7636,2019,null,0,null,0.00000,0.014,0,106,Zimbabwe

In [80]:

data_clean[0]
data_clean[1]
data_clean[-1]

['Year',
 'Fossil fuels electricity generation',
 'Geothermal electricity generation',
 'Hydroelectricity generation',
 'Nuclear power generation',
 'Solar electricity generation',
 'Wind electricity generation']

['1980', '0.716', '0', '2.91900', '0.00000', '0', '0']

['2019', '0', '0', '5.15394', '0.00000', '0.022', '0']

In [83]:
df_albania = pd.DataFrame(data_clean[1:], columns=data_clean[0])

In [84]:
df_albania['country_id']=179